config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  
  namespace :admin do
    get '/' => 'homes#top'
  end
  
  
  scope module: :user do
    get '/' => 'homes#top'
    root to: "homes#top"
    resources :notifications, only: :index
    resources :homes, only: [:top, :about]
    resources :users
    resources :books do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  #バリデーション
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    has_many :books, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy

    has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
    has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
    
 #既にいいねしているかどうか
 def already_liked?(book)
   self.likes.exists?(book_id: book.id)
 end
end

app/controllers/user/books_controller.rb
class User::BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def index
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
    #新着順で表示
    @comments = @book.comments.order(created_at: :desc)
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.fins(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body, :author, :user_id)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    #投稿に紐づいたコメントを作成
    @comment = @book.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    render :index
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :ibook_id, :user_id)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  before_action :book_params
  def create
      like = current_user.likes.new(book_id: @book.id)
      like.save
      @book = Book.find(params[:book_id])
      #通知の作成
      @book.create_notification_by(current_user)
      respond_to do |format|
        format.html {redirect_to request.referrer}
        format.js
      end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, book_id: @book.id).destroy
  end

  private
  def book_params
    @book = Book.find(params[:book_id])
  end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  def index
    #current_userの投稿に紐づいた通知一覧
      @notifications = current_user.passive_notifications
    #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
      @notifications.where(checked: false).each do |notification|
          notification.update_attributes(checked: true)
      end
  end

  def destroy_all
    #通知を全削除
      @notifications = current_user.passive_notifications.destroy_all
      redirect_to notifications_path
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
  end
  
  def show 
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/books_helper.rb
module User::BooksHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/notifications_helper.rb
module User::NotificationsHelper

  def notification_form(notification)
      @visiter = notification.visiter
      @comment = nil
      your_item = link_to 'あなたの投稿', book_path(notification), style:"font-weight: bold;"
      # @visiter_comment = notification.comment_id
      #notification.actionがfollowかlikeかcommentか
      case notification.action
        when "follow" then
          tag.a(notification.visiter.nickname, href:user_path(@visiter), style:"font-weight: bold;")+"があなたをフォローしました"
        when "like" then
          tag.a(notification.visiter.nickname, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:book_path(notification.book_id), style:"font-weight: bold;")+"にいいねしました"
        # when "comment" then
        #     @comment = Comment.find_by(id: @visiter_comment)&.content
        #     tag.a(@visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:book_path(notification.book_id), style:"font-weight: bold;")+"にコメントしました"
      end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/comments/_form.html.erb
<!-- コメント入力フォーム ------------------------------------------------------------>
<%= form_with model: [book, comment], url: book_comments_path(@book)  do |f| %>
    <%= f.text_area :content, class: "input-mysize" %>
    <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/user/comments/_index.html.erb
<!-- コメント内容(２件) ------------------------------------------------------------------>
<%= comments.count %>件コメント
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<% comments.first(2).each do |comment| %>
  <% unless comment.id.nil? %>
    <li class="comment-container">
        <div class="comment-box">
            <div class="comment-text">
                <p><%= link_to "@#{comment.user.nickname}", user_path(comment.user.id) %></p>
                <div class="comment-entry">
                    <%= comment.content %>
                    <% if comment.user == current_user %>
                        <%= link_to book_comment_path(comment.book_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                            <i class="fas fa-trash" style="color: black;"></i>
                        <% end %>
                    <% end %>
                </div>
                <span class="comment-date pull-right">
                      <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                </span>
            </div>
        </div>
    </li>
  <% end %>
<% end %>
<!-- コメント内容(3件目以降) ------------------------------------------------------------------>
    <div class="collapse" id="collapseExample">
            <% comments.offset(2).each do |comment| %>
              <% unless comment.id.nil? %>
                <li class="comment-container">
                    <div class="comment-box">
                        <div class="comment-text">
                            <p><%= link_to "@#{comment.user.nickname}", user_path(comment.user.id) %></p>
                            <div class="comment-entry">
                                <%= comment.content %>
                                <% if comment.user == current_user %>
                                    <%= link_to book_comment_path(comment.book_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                                        <i class="fas fa-trash" style="color: black;"></i>
                                    <% end %>
                                <% end %>
                            </div>
                            <span class="comment-date pull-right">
                                  <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                            </span>
                        </div>
                    </div>
                </li>
              <% end %>
            <% end %>
    </div>