config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  
  namespace :admin do
    get '/' => 'homes#top'
  end
  
  
  scope module: :user do
    get '/' => 'homes#top'
    root to: "homes#top"
    resources :notifications, only: :index
    resources :homes, only: [:top, :about]
    resources :users
    resources :books do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  #refile
  attachment :image
  
  has_many :notifications, dependent: :destroy
  
  def create_notification_by(current_user)
      notification = current_user.active_notifications.new(
        book_id: id,
        visited_id: user_id,
        action: "like"
      )
      notification.save if notification.valid?
  end

  # def create_notification_comment!(current_user, comment_id)
  #     # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
  #     temp_ids = Comment.select(:user_id).where(book_id: id).where.not(user_id: current_user.id).distinct
  #     temp_ids.each do |temp_id|
  #         save_notification_comment!(current_user, comment_id, temp_id['user_id'])
  #     end
  #     # まだ誰もコメントしていない場合は、投稿者に通知を送る
  #     save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  # end

  # def save_notification_comment!(current_user, comment_id, visited_id)
  #     # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
  #   notification = current_user.active_notifications.new(
  #     book_id: id,
  #     comment_id: comment_id,
  #     visited_id: visited_id,
  #     action: 'comment'
  #   )
  #   # 自分の投稿に対するコメントの場合は、通知済みとする
  #   if notification.visiter_id == notification.visited_id
  #     notification.checked = true
  #   end
  #   notification.save if notification.valid?
  # end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  #バリデーション
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/notification.rb
class Notification < ApplicationRecord
  #スコープ(新着順)
  default_scope->{order(created_at: :desc)}

  belongs_to :book, optional: true
  # belongs_to :comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    has_many :books, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy

    has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
    has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
    
 #既にいいねしているかどうか
 def already_liked?(book)
   self.likes.exists?(book_id: book.id)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   
  def after_sign_in_path_for(resource)
    books_path(resource)
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/user/books_controller.rb
class User::BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def index
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
    #新着順で表示
    @comments = @book.comments.order(created_at: :desc)
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.fins(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body, :author, :user_id)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    #投稿に紐づいたコメントを作成
    @comment = @book.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    render :index
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :ibook_id, :user_id)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  before_action :book_params
  def create
      like = current_user.likes.new(book_id: @book.id)
      like.save
      @book = Book.find(params[:book_id])
      #通知の作成
      @book.create_notification_by(current_user)
      respond_to do |format|
        format.html {redirect_to request.referrer}
        format.js
      end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, book_id: @book.id).destroy
  end

  private
  def book_params
    @book = Book.find(params[:book_id])
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
  end
  
  def show 
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/user/books_helper.rb
module User::BooksHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/notifications_helper.rb
module User::NotificationsHelper

  def notification_form(notification)
      @visiter = notification.visiter
      @comment = nil
      your_item = link_to 'あなたの投稿', book_path(notification), style:"font-weight: bold;"
      # @visiter_comment = notification.comment_id
      #notification.actionがfollowかlikeかcommentか
      case notification.action
        when "follow" then
          tag.a(notification.visiter.nickname, href:user_path(@visiter), style:"font-weight: bold;")+"があなたをフォローしました"
        when "like" then
          tag.a(notification.visiter.nickname, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:book_path(notification.book_id), style:"font-weight: bold;")+"にいいねしました"
        # when "comment" then
        #     @comment = Comment.find_by(id: @visiter_comment)&.content
        #     tag.a(@visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:book_path(notification.book_id), style:"font-weight: bold;")+"にコメントしました"
      end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      
        <%= link_to root_path do %>
          <p id="logo-head"><%= image_tag 'sharebook.logo.png', :size => '150x75' %></p>
        <% end %>
        <ul class="navbar-nav ml-auto">
           
        <% if user_signed_in? %>
          <p class="welcome"> ようこそ、<strong><%= current_user.nickname%></strong> さん！</p>
          <li class="nav-item">
            <%= link_to "TOP", root_path, class: 'btn' %>
          </li><br>
          <li class="nav-item">
            <%= link_to "マイページ", user_path(current_user.id), class: 'btn' %>
          </li><br>
          <li class="nav-item">
            <%= link_to "ユーザー一覧", users_path, class: 'btn' %>
          </li><br>
          <li class="nav-item">
            <%= link_to '新規投稿', new_book_path, class: 'btn' %>
          </li><br>
          <li class="nav-item">
            <%= link_to "ブック一覧", books_path, class: 'btn' %>
          </li><br>
          <% if unchecked_notifications.any? %>
            <!--<i class="fa fa-circle" style="color: gold;"></i>-->
          <% end %>
          <li>
            <%= link_to "NOTICE", notifications_path, class: "btn-default" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn' %>
          </li>

        <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn' %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "TOP", root_path, class: 'btn' %>
          </li><br>
          <li class="nav-item">
            <%= link_to "登録する", new_user_registration_path, class: 'btn' %>
          </li><br>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'btn' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/header' %>
  <body>
    
    <%= yield %>
  </body>
</html>